sharev2: manage replica quotas transparently
sapcc/limes pull request #109
Opened 2021-03-05 13:39 UTC by majewsky

@Carthaca Can you double-check that this has the correct semantics?

2021-03-12 17:23 UTC, Carthaca requested changes
I'm not sure if will be safe to enable the `replication_enabled` flag that comes with this change. Please answer my inline questions.

And out of curiosity: is there a reason why you sometimes use `shareTypeName` and in other places `stName`?

2021-03-15 13:46 UTC, majewsky commented on pkg/plugins/manila.go
> -
Yes. If no share type has `replication_enabled: true`, Limes should not touch replica quotas and thus behave exactly like before.

2021-03-15 13:48 UTC, majewsky commented on pkg/plugins/manila.go
> +		}
Your assessment is correct. Deploying Limes is rather straightforward, though, so we should be able to work this out in practice.

2021-03-15 13:49 UTC, majewsky commented
> And out of curiosity: is there a reason why you sometimes use `shareTypeName` and in other places `stName`?

I initially had `shareTypeName` everywhere, but it's quite bulky, so I shortened it to `stName` inside all loops over share types, where the surrounding code provides sufficient context to infer that "st" is "share type".

2021-03-24 08:53 UTC, Carthaca approved these changes

2021-03-24 12:51 UTC, merged