WIP
sapcc/limes pull request #134
Opened 2022-03-04 09:40 UTC by SuperSandro2000

Checklist:

- [ ] If this PR is about a plugin, I tested the plugin against an OpenStack cluster.
- [ ] I updated the documentation to describe the semantical or interface changes I introduced.

2022-03-04 10:14 UTC, majewsky reviewed
Some early remarks. I'm explicitly focusing on the large scale here.

2022-03-04 10:14 UTC, majewsky commented on limes.rego
> +output = {"allow": true, "message": null} {
As discussed on the phone, a more useful input/output setup for the policy would be to generate a DomainReport or ProjectReport representing the desired state of the domain or project after the requested quota has been applied (i.e. deep-copy the existing report and adjust `Quota` and `DesiredBackendQuota` to match the requested values).

With this change in input format, the output format should also change to report as many error messages at once as possible, to match the error reporting style of QuotaUpdater (where we support reporting one error message per requested quota). OPA Gatekeeper has a similar setup, wherein the policy returns a list of violations, and an empty list is interpreted as acceptance. With this pattern, the policy from the testcase could look like this:

```rego
package limes

violation[{ "msg": msg, "service": "shared", "resource": "things" }] {
  input.TargetProjectReport.Services["shared"].Resources["capacity"].Quota == 0
  msg := "must allocate shared/things quota before"
}
```

2022-03-04 10:14 UTC, majewsky commented on pkg/core/config.go
> +	PreparedRegoQuery    rego.PreparedEvalQuery           `yaml:"-"`
I'm not anticipating much overlap in the checks that OPA policies will be used for on project level and domain level, respectively. Therefore please split domain-level and project-level checks into two separate policies:
```suggestion
	OPA  OPAConfiguration                           `yaml:"opa"`
```

where
```go
type OPAConfiguration struct {
  ProjectQuotaPolicyPath string `yaml:"project_quota_policy_path"`
  ProjectQuotaQuery rego.PreparedEvalQuery `yaml:"-"`
  DomainQuotaPolicyPath string `yaml:"domain_quota_policy_path"`
  DomainQuotaQuery rego.PreparedEvalQuery `yaml:"-"`
}
```

2022-03-09 12:49 UTC, majewsky requested changes

2022-03-09 12:49 UTC, majewsky commented on pkg/api/quota_updater.go
> +					logg.Error("%#v", resultViolation["msg"])
The error message should describe what is happening, not least to make it easier to find the respective log in Kibana when a user reports the user-visible error message to us.

2022-03-09 12:49 UTC, majewsky commented on pkg/api/quota_updater.go
> +				logg.Error("OPA violation has wrong format: %s", reflect.TypeOf(resultViolation))
You can simplify this with the `%T` format directive:
```suggestion
				logg.Error("OPA violation has wrong format: %T", resultViolation)
```

2022-03-09 12:49 UTC, majewsky commented on pkg/api/quota_updater.go
> +		logg.Error("OPA returned unsupported data: %#s", results[0].Bindings)
`#` is not supported for `%s` as far as I know. Did you mean `%#v`?

2022-03-09 12:50 UTC, majewsky commented on pkg/api/api_test.go
> +	clusterConfig.SetupOPA("fixtures/dummy.rego")
Why do we need a dummy file here? We should support having no policy at all for backwards-compatibility and simplicity.

2022-03-09 12:52 UTC, SuperSandro2000 commented on pkg/core/config.go
> +	PreparedRegoQuery    rego.PreparedEvalQuery           `yaml:"-"`
It's just easier to have everything in one file and spares us a lot of code duplication.

```rego
package limes

violation[{ "msg": msg, "service": "shared", "resource": "things" }] {
  input.targetdomainreport....
}

violation[{ "msg": msg, "service": "shared", "resource": "things" }] {
  input.targetprojectreport.....
}
```

2022-03-09 12:55 UTC, majewsky commented on pkg/core/config.go
> +	PreparedRegoQuery    rego.PreparedEvalQuery           `yaml:"-"`
I'm willing to accept a bit of code duplication for increased clarity. When someone looks at the policy in our config two years down the line, I don't want there to be any unnecessary confusion between what is a domain-level policy and what is a project-level policy. Both look so similar (both in structure and in names like `targetdomainreport` vs. `targetprojectreport`) that they will be very likely confused.

2022-03-09 13:09 UTC, SuperSandro2000 commented on pkg/api/api_test.go
> +	clusterConfig.SetupOPA("fixtures/dummy.rego")
Now I am skipping the entire OPA section when the file is missing. Otherwise we get a nil point dereference [here](https://github.com/sapcc/limes/blob/888f039803e0f3975051109b2a868f0ce01b9222/pkg/api/quota_updater.go#L523) and if the rego file does not contain some boilerplate the we don't get any output and other errors trigger.

2022-03-10 10:49 UTC, majewsky approved these changes
I've added a small change to make the `opa` config section optional (otherwise the first deployment after merge will fail), and I've also added some basic documentation. With this, this is good to go in from my PoV.

2022-03-10 12:25 UTC, merged