Add API endpoint for scrape errors
sapcc/limes pull request #137
Opened 2022-03-15 17:41 UTC by talal

Checklist:

- [ ] If this PR is about a plugin, I tested the plugin against an OpenStack cluster.
- [x] I updated the documentation to describe the semantical or interface changes I introduced.

2022-03-16 14:19 UTC, talal commented
I've put the PR as draft as I still need to add rates scrape error reporting.

2022-03-22 09:29 UTC, majewsky requested changes

2022-03-22 09:29 UTC, majewsky commented on pkg/reports/error.go
> +	HAVING ps.scrape_error_message != ''
- `LEFT OUTER JOIN` can be replaced by `JOIN` since the `ps.scrape_error_message != ''` condition makes it impossible to have partially-null result rows.
- `GROUP BY` is not necessary since no aggregate functions are used and the query will never produce multiple rows for one project service (with basically the same justification as in the previous point).
- 
```suggestion
	  JOIN domains d ON d.id = p.domain_id
	  JOIN project_services ps ON ps.project_id = p.id
	WHERE %s AND ps.scrape_error_message != ''
```

2022-03-22 09:29 UTC, majewsky commented on pkg/reports/error.go
> +		var checkedAtAsTime *time.Time
When initializing to a zero value, it's more idiomatic to just declare the variable in that type.
```suggestion
		var (
			sErr ScrapeError
			checkedAtAsTime *time.Time
		)
```

2022-03-22 09:29 UTC, majewsky commented on pkg/api/fixtures/scrape-error-list.json
> +      },
I like the idea of grouping multiple similar errors together, but not having any actual project IDs in here would make it harder to investigate in cases where multiple projects are affected, but not all of them are. Please show the identity of one of the affected projects, and add a field like `affected_projects` containing the number of affected projects if that number is not 1. Then we can display in the UI something like `Project: myproject@mydomain (+10 more)`.

2022-03-24 12:09 UTC, majewsky approved these changes
I fixed an error that CodeQL found. With that, this is good to go in.

2022-03-24 12:09 UTC, merged