Move some settings into environment variables
sapcc/limes pull request #229
Opened 2022-08-03 15:19 UTC by SuperSandro2000

Checklist:

- [ ] If this PR is about a plugin, I tested the plugin against an OpenStack cluster.
- [ ] I updated the documentation to describe the semantical or interface changes I introduced.

TODO: update https://github.com/sapcc/limes/blob/master/docs/operators/config.md

2022-08-04 13:23 UTC, majewsky requested changes

2022-08-04 13:23 UTC, majewsky commented on docs/operators/config.md
> +| `OS_INTERFACE` | no | The endpoint type Limes should use for the OpenStack services. |
There are lots of other variations of configuration that are supported by gophercloud/utils/clientconfig. For other services, I usually point to the upstream documentation for openstackclient, see e.g. https://github.com/sapcc/tenso/blob/183c721f334e86cab344afb5c3018acc1c28226d/README.md?plain=1#L63

2022-08-04 13:23 UTC, majewsky commented on docs/operators/config.md
> +| `LIMES_OPA_DOMAIN_QUOTA_POLICY_PATH` | yes, when `opa` section is given | Like `opa.project_quota_policy_path`, but this policy is used for validating domain quota changes instead. |
```suggestion
| `LIMES_OPA_DOMAIN_QUOTA_POLICY_PATH` | yes, when `opa` section is given | Like `LIMES_OPA_PROJECT_QUOTA_POLICY_PATH`, but this policy is used for validating domain quota changes instead. |
```

2022-08-04 13:23 UTC, majewsky commented on docs/operators/config.md
> +The configuration file options relating to the targeted OpenStack cluster. A minimal config file could look like this:
While we're at it, we should fix the broken grammar in this line.
```suggestion
Furthermore, a YAML file must be provided that describes things like the set of available backend services and the quota/capacity scraping behavior. A minimal config file could look like this:
```

2022-08-04 13:23 UTC, majewsky commented on pkg/api/audit.go
> +			User:   url.UserPassword(osext.GetenvOrDefault("LIMES_AUDIT_RABBITMQ_USERNAME", "rabbitmq"), os.Getenv("LIMES_AUDIT_RABBITMQ_PASSWORD")),
This does not match the documented behavior:
```suggestion
			User:   url.UserPassword(osext.GetenvOrDefault("LIMES_AUDIT_RABBITMQ_USERNAME", "guest"), osext.GetenvOrDefault("LIMES_AUDIT_RABBITMQ_PASSWORD", "guest")),
```

2022-08-04 13:23 UTC, majewsky commented on pkg/api/audit.go
> +		}.Commit(rabbitURI, osext.GetenvOrDefault("LIMES_AUDIT_QUEUE_NAME", "notifications.info"))
This does not match the documented behavior:
```suggestion
		}.Commit(rabbitURI, osext.MustGetenv("LIMES_AUDIT_QUEUE_NAME"))
```

2022-08-04 13:23 UTC, majewsky commented on pkg/core/auth.go
> -		AllowReauth:      true,
The new codepath does not set AllowReauth, which is an error for a long-running service. Compare e.g. https://github.com/sapcc/tenso/blob/183c721f334e86cab344afb5c3018acc1c28226d/internal/tenso/config.go#L69

2022-08-04 13:23 UTC, majewsky commented on pkg/core/cluster.go
> +		c.QuotaConstraints, errs = NewQuotaConstraints(c, os.Getenv("LIMES_CONSTRAINTS_PATH"))
A double invocation of `os.Getenv()` is not good style. The value should be put into a variable first.

2022-08-04 13:23 UTC, majewsky commented on pkg/core/config.go
>  }
Since the paths are not part of the bigger YAML data structure anymore, we don't need to store them here anymore. This then enables a simplification of how this is set up at runtime vs. at test time. Please change `func SetupOPA` to take both paths as arguments, and then provide them directly at that function's callsites.

2022-08-04 13:23 UTC, majewsky commented on pkg/core/config.go
>  	}
This is not required anymore when MustGetenv is used for `LIMES_AUDIT_QUEUE_NAME` like I suggested above.

2022-08-19 13:15 UTC, majewsky commented
@SuperSandro2000 I made some changes on top of your changes to improve the structure of the code and docs. Also, I think I fixed a bug that the tests did not catch (see commit messages). Please counter-review.

2022-08-19 13:27 UTC, majewsky approved these changes
If you agree with my changes, this can be merged together with the Helm chart change and the secrets change.

2022-08-22 09:38 UTC, SuperSandro2000 commented on docs/operators/config.md
> +| `LIMES_OPA_PROJECT_QUOTA_POLICY_PATH` | yes, when `opa` section is given | Path to a Rego file. This policy will be evaluated whenever a user tries to change a project quota. If the policy reports
```suggestion
| `LIMES_OPA_DOMAIN_QUOTA_POLICY_PATH` | yes, when `opa` section is given | Path to a Rego file. This policy will be evaluated whenever a user tries to change a domain quota. If the policy reports any violations, the PUT will fail and the generated error messages will be reported to the user. See [../example-quota-policy.rego](../example-quota-policy.rego) for an example illustrating the expected structure of the policy. |
| `LIMES_OPA_PROJECT_QUOTA_POLICY_PATH` | yes, when `opa` section is given | Like `LIMES_OPA_PROJECT_QUOTA_POLICY_PATH`, but this policy is used for validating project quota changes instead. |
```

2022-08-22 11:34 UTC, majewsky commented on docs/operators/config.md
> +| `LIMES_OPA_PROJECT_QUOTA_POLICY_PATH` | yes, when `opa` section is given | Path to a Rego file. This policy will be evaluated whenever a user tries to change a project quota. If the policy reports
Done.

2022-08-22 14:32 UTC, merged