fill PerAZ field in ClusterResourceReport
sapcc/limes pull request #376
Opened 2023-11-01 13:23 UTC by majewsky

Same behavior as for ProjectResourceReport: It's gated behind the "v2 preview" feature flag. Also, this bumps go-api-declarations twice because I realized how many fields were missing from ClusterAZResourceReport halfway through.

2023-11-01 16:02 UTC, VoigtS requested changes

2023-11-01 16:02 UTC, VoigtS commented on internal/api/fixtures/cluster-get-west-with-overcommit-and-v2-api.json
> +            "per_az": {
I noticed this is the cluster based view. Therefore the AZ usage is also cluster based. But what does "projects_usage" refer to then?

2023-11-02 09:20 UTC, majewsky commented on internal/api/fixtures/cluster-get-west-with-overcommit-and-v2-api.json
> +            "per_az": {
Quoting from https://github.com/sapcc/go-api-declarations/blob/main/limes/resources/report_cluster.go:

> Usage is what the backend reports. This is only shown if the backend does indeed report a summarized cluster-wide usage level.
> ProjectsUsage is the aggregate of the usage across all projects, as reported by the backend on the project level.

Both can differ for two reasons: They are collected on different schedules, so usage can and will change between one and collection time and the other. And also there could be resources that exist on the hardware level without being managed by OpenStack. Those would be reported on the cluster-level usage, but not on the project-level usage since they cannot be associated with any one project.

Having both here is primarily interesting for reporting purposes.

2023-11-02 09:24 UTC, VoigtS approved these changes

2023-11-02 11:54 UTC, merged