Add Skeleton transferCommitment endpoint
sapcc/limes pull request #410
Opened 2024-03-05 13:55 UTC by VoigtS

productionChecklist:
- [ ] I updated the documentation to describe the semantical or interface changes I introduced.

This PR introduces commitment transfers from a source to a target project.
Two API's will be implemented:
- [x] start-transfer: Either marks a commitment as transferrable or splits the commitment into two parts where the provided amount will be the indicator for the transferrable commitment
- [ ] transfer-commitment: Where the actual commitment transfer from a source to a target AZ_RESOURCE_ID will be executed.

2024-03-11 14:08 UTC, SuperSandro2000 commented on docs/users/api-spec-resources.md
> +    "transfer_status": "unlisted",
```suggestion
    "transfer_status": "unlisted"
```

That's not valid json 🙈

2024-03-11 14:08 UTC, SuperSandro2000 commented on docs/users/api-spec-resources.md
> +    "transfer_status": "unlisted",
```suggestion
    "transfer_status": "unlisted"
```

2024-03-11 14:08 UTC, SuperSandro2000 commented on docs/users/api-spec-resources.md
> +Transfers the commitment from a source project to a target project. This endpoint receives the target project ID, but the commitment ID from the source project. Requires a generated token from the AP
```suggestion
Transfers the commitment from a source project to a target project.
This endpoint receives the target project ID, but the commitment ID from the source project.
Requires a generated token from the API: `/v1/domains/:id/projects/:id/commitments/:id/start-transfer`.
On success the API clears the `transfer_token` and `transfer_status` from the commitment.
After that, it returns the commitment as a JSON document.  
```

2024-03-11 14:08 UTC, SuperSandro2000 commented on internal/api/commitment.go
> +		return
Shouldn't we return an error here?

2024-03-11 14:08 UTC, SuperSandro2000 commented on internal/api/commitment_test.go
> +	var confirmBy = time.Now().Unix()
Shouldn't we use the mock clock here?

2024-03-11 14:08 UTC, SuperSandro2000 commented on internal/api/utils.go
> +	tokenBytes := make([]byte, 12)
```suggestion
	tokenBytes := make([]byte, 24)
```
maybe 12 is a bit short

2024-03-11 14:41 UTC, VoigtS commented on internal/api/commitment_test.go
> +	var confirmBy = time.Now().Unix()
That slipped through. Thank you.

2024-03-15 10:11 UTC, majewsky requested changes
Please do not be disheartened by the number of remarks. You did a good job getting accustomed to the existing code structure and following house conventions. But there is some work left to do, both in the stylistic and functional departments:

2024-03-15 10:11 UTC, majewsky commented on internal/api/commitment.go
> +	if req.Amount >= dbCommitment.Amount {
A requested amount greater than the commitment amount should be treated as an error and caught during validation.

2024-03-15 10:11 UTC, majewsky commented on internal/api/commitment.go
> +func (p *v1Provider) splitCommitment(dbCommitment db.ProjectCommitment, amount uint64) db.ProjectCommitment {
This does not actually "do" anything to the database, as the name implies. I suggest the following name instead:
```suggestion
func (p *v1Provider) buildSplitCommitment(dbCommitment db.ProjectCommitment, amount uint64) db.ProjectCommitment {
```
I'm also open to other suggestions if you have any.

2024-03-15 10:11 UTC, majewsky commented on internal/api/commitment.go
> +		respondwith.ErrorText(w, errors.New("no transfer token provided"))
`respondwith.ErrorText` sends a 500 response (Internal Server Error) and thus should not be used for client errors. `http.Error` is the correct choice here.

2024-03-15 10:11 UTC, majewsky commented on internal/api/commitment_test.go
> +	req1 := func(transfer_status string) assert.JSONObject {
Go does not usually use snake_case:
```suggestion
	req1 := func(transferStatus string) assert.JSONObject {
```

2024-03-15 10:11 UTC, majewsky commented on internal/api/commitment_test.go
> +		ExpectBody:   assert.JSONObject{"commitment": resp1},
Continuing from my previous remark earlier in the request body parsing, this should only send the required attributes. (And when creating the commitment, `transfer_status` and `transfer_token` should not be sent because those are not applicable for the `/new` endpoint.) The test should be clear about what is actually required to induce the expected behavior.

2024-03-15 10:11 UTC, majewsky commented on internal/api/commitment_test.go
> +	}.Check(t, s.Handler)
When checking error cases, please also check that the error message matches the expected error condition:
```go
ExpectBody: assert.StringData("something something\n"),
```

2024-03-15 10:11 UTC, majewsky commented on internal/api/core.go
> +func (p *v1Provider) OverrideGenerateToken(generateTransferToken func() string) *v1Provider {
I would like this naming to be more consistent:
```suggestion
func (p *v1Provider) OverrideGenerateTransferToken(generateTransferToken func() string) *v1Provider {
```

2024-03-15 10:11 UTC, majewsky commented on internal/api/utils.go
> +func GenerateToken() string {
Picking up from the naming remark from before:
```suggestion
func GenerateTransferToken() string {
```
Also, please add a docstring to explain the usage context.

2024-03-15 14:52 UTC, VoigtS commented on internal/api/commitment_test.go
> +		ExpectBody:   assert.JSONObject{"commitment": resp1},
Fixed: this was a misunderstanding. The resource body should contain the commitment.

2024-03-15 14:53 UTC, VoigtS commented on internal/api/utils.go
> +func GenerateToken() string {
Please check the docstring that I added to the function.

2024-03-15 15:43 UTC, VoigtS commented
Reminder: Check on Monday - Previous OLTP implementation had a bug in the transferred commitment.
Only the return value contained the Transferstatus and Token of the splitted commitment `transferCommitment`.
However, the values were not mirrored in the database.

The ORM implementation now takes this into account and saves the values in the database. A additional test case was added that tests the transfer of a splitted commitment.

2024-03-19 12:21 UTC, majewsky requested changes

2024-03-19 12:21 UTC, majewsky commented on internal/api/commitment.go
> +	err := p.DB.SelectOne(&dbCommitment, getCommitmentWithMatchingTransferTokenQuery, transferToken)
Should also match on ID, as defense in depth.

2024-03-19 12:21 UTC, majewsky commented on internal/api/commitment.go
> +	err = p.DB.QueryRow(findTargetAZResourceIDBySourceIDQuery, targetProject.ID, dbCommitment.AZResourceID).Scan(&targetResourceID)
This looks like it does not match on service type and resource name. How is the commitment matched to the correct service and resource on the receiving side?

The tests can plausibly work "by accident" because they all use `first/capacity` which is the alphabetically first service/resource.

2024-03-19 15:20 UTC, VoigtS commented on internal/api/commitment.go
> +	err := p.DB.SelectOne(&dbCommitment, getCommitmentWithMatchingTransferTokenQuery, transferToken)
The query now respects the commitment ID (read out of the URL)

2024-03-19 15:41 UTC, VoigtS commented
Fixed: Movement of the transfer token from queryString into the request header.

2024-03-21 12:31 UTC, majewsky approved these changes

2024-03-21 12:31 UTC, merged