Add GET commitment by token endpoint
sapcc/limes pull request #502
Opened 2024-07-25 12:58 UTC by VoigtS

The transfer commitment endpoint is fine in scenarios when it get called after the start-transfer endpoint, because it returns the commitment first.
Because new requirments arise that require to transfer a commitment between projects, the start-transfer endpoint and the transfer endpoint are now decoupled from each other. To mitigate this, I would like to introduce an endpoint that gets a commitment by its token.

This approach also ensures that a commitment can be checked for its details (resource, AZ) before it actually gets transferred to the target project. This is a important detail for the UI.

2024-07-25 13:14 UTC, majewsky requested changes
Some nitpicks, some larger comments.

2024-07-25 13:14 UTC, majewsky commented on docs/users/api-spec-resources.md
> +### GET "/v1/domains/:id/projects/:id/commitments/:token"
Style nitpick:
```suggestion
### GET /v1/domains/:id/projects/:id/commitments/:token
```

2024-07-25 13:14 UTC, majewsky commented on internal/api/commitment.go
> +		SELECT * from project_commitments where transfer_token = $1
Style nitpick:
```suggestion
		SELECT * FROM project_commitments WHERE transfer_token = $1
```

2024-07-25 13:14 UTC, majewsky commented on internal/api/commitment.go
> +		http.Error(w, "commitment unexpectingly not found.", http.StatusNotFound)
```suggestion
		http.Error(w, "commitment unexpectedly not found.", http.StatusNotFound)
```

2024-07-26 10:48 UTC, VoigtS commented on internal/api/commitment.go
> +	}
For now I solved it with a partial index on the` transfer_token` column. It turned out the default value for this column is an empty string wich collides with a unique constraint. Because updating all the type definitions and implementations doesn't really feel worth it to implement a NULL column, I settled with this for now. What do you think about it?

2024-07-26 12:27 UTC, majewsky requested changes

2024-07-26 12:27 UTC, majewsky commented on internal/api/commitment.go
> +		http.Error(w, "insufficient access rights.", http.StatusForbidden)
Require() already writes an error message, so this line is superfluous.

2024-07-26 12:27 UTC, majewsky commented on internal/api/commitment.go
> +	}
This check is unreachable and can be removed. gorilla/mux already requires at least 1 character on each variable match.

2024-07-26 12:27 UTC, majewsky commented on internal/db/migrations.go
> +	`,
Please also add a down migration, even if only for completeness sake.

2024-07-26 12:38 UTC, VoigtS commented on internal/api/commitment.go
> +		http.Error(w, "insufficient access rights.", http.StatusForbidden)
You are right, I had a similar case on the TransferCommitment endpoint which I cleaned up too.

2024-07-26 12:40 UTC, VoigtS commented on internal/db/migrations.go
> +	`,
I added an empty down migration now.

2024-07-26 14:26 UTC, VoigtS commented
@majewsky Please check out #508 as an alternative solution proposition.

2024-07-29 08:31 UTC, VoigtS commented
Cancelling this PR, due to #508

2024-07-29 08:31 UTC, closed without merging