refactor metadata types on the QuotaPlugin API
sapcc/limes pull request #516
Opened 2024-08-08 13:17 UTC by majewsky

The reasoning is explained in the individual commit messages. Since all three commits are completely unrelated to each other, I recommend reviewing each separately.

2024-08-08 15:35 UTC, VoigtS requested changes

2024-08-08 15:35 UTC, VoigtS commented on internal/reports/domain.go
>  		}
I'm not sure. Is it okay for us to have a naming duplication between the liquid structure (HasQuota) and the internal structure (NoQuota)?

2024-08-09 11:46 UTC, majewsky commented on internal/reports/domain.go
>  		}
The "internal structure" is specifically a data structure associated with the v1 API. In v2, this will not be a concern at all, because that one will be built around `liquid.ResourceInfo` from the get-go. So NoQuota will fall out of use at latest when the v1 API is eventually removed.

Core business logic already only sees `liquid.ResourceInfo` and thus uses HasQuota, whereas report generating code for the v1 API sometimes only has a `limesresources.ResourceInfo` because of how it is structured, and therefore it uses NoQuota. The latter is generated from the former and we use whatever we have available.

For what it's worth, since NoQuota is not reflected in the API, we could replace this field with a HasQuota field to match the liquid format. If that is desired, I can make a PR in go-api-declarations.

2024-08-09 11:48 UTC, VoigtS commented on internal/reports/domain.go
>  		}
No, I think it is fine regarding the change from v1 to v2. Thanks for the clarification.

2024-08-09 11:48 UTC, VoigtS approved these changes

2024-08-09 13:14 UTC, merged