Add POST API to convert a commitment to a target Resource
sapcc/limes pull request #554
Opened 2024-09-11 14:08 UTC by VoigtS

This PR aims to introduce the POST API to convert a supported commitment from a source to a target resource.

2024-09-11 14:59 UTC, majewsky requested changes
First pass. I don't think I caught everything, but I have to leave soon, so I will leave it at that for now

2024-09-12 08:22 UTC, VoigtS commented on internal/api/commitment.go
> +    `)
The query is now inline.

2024-09-12 08:23 UTC, VoigtS commented on internal/api/commitment.go
> +	httpapi.IdentifyEndpoint(r, "/v1/domains/:domain_id/projects/:project_id/commitment-conversion/:commitment_id")
You are correct. The initial implementation did not take the conversion to a different project into account, leading to an unconsistent path in the end, this is now fixed.

2024-09-12 08:48 UTC, VoigtS commented on internal/api/commitment.go
> +	if (sourceBehavior.CommitmentConversion == core.CommitmentConversion{} || targetBehavior.CommitmentConversion == core.CommitmentConversion{}) {
This one was a basd oversight, I also included a test that checks for a conversion to a invalid different identifier.

2024-09-12 09:02 UTC, VoigtS commented on internal/api/commitment.go
> +		http.Error(w, "domain not found.", http.StatusNotFound)
I removed them also on the findProjectRequests. We are clean on this part now. Thanks for the info.

2024-09-12 12:04 UTC, VoigtS commented on internal/api/commitment.go
> +	}
You are correct, the conversion rounding was later corrected with the addition of the remainder.
The implementation now rejects all requests where `req.SourceAmount % fromAmount > 0`.

2024-09-12 12:06 UTC, VoigtS commented on internal/api/commitment.go
> +		}
The updated implementation now supersedes the old commitment.
It creates a `remainderCommitment` with Amount: `dbCommitment.Amount - req.SourceAmount`
and a `convertedCommitment` with Amount: `(req.SourceAmount / fromAmount) * toAmount`

2024-09-13 13:51 UTC, majewsky reviewed
I once again did not have enough time to complete the review today... Sorry.

2024-09-13 13:51 UTC, majewsky commented on internal/api/commitment.go
> +	if req.SourceAmount <= 0 || req.SourceAmount > dbCommitment.Amount {
SourceAmount is unsigned:
```suggestion
	if req.SourceAmount > dbCommitment.Amount {
```

2024-09-16 11:14 UTC, VoigtS commented on internal/api/commitment.go
> +		http.Error(w, "unable to convert unconfirmed commitments", http.StatusConflict)
You are right, it is possible to do that. I implemented this now.
* I removed the early confirm_By check.
* Instead, the canConvertCommitment part only gets executed if the commitment has no confirm_by field.
* I added a unit test.

2024-09-16 12:00 UTC, VoigtS commented on internal/api/commitment.go
> +		http.Error(w, "unable to convert unconfirmed commitments", http.StatusConflict)
This also fixed a bug. Previously a commitment with the exact amount that it should be transferred as (in this case `amount: 3` would create a commitment with remainingAmount=0.
That's because the previous check was removed, but not reintigrated to check this case.

2024-09-17 12:26 UTC, majewsky requested changes
We're getting there.

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment.go
> +	}
I think we can do without this. There should be a route to vacating a resource of commitments while still allowing maintenance on existing commitments.

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment.go
> +		http.Error(w, "commitment is not convertible", http.StatusUnprocessableEntity)
```suggestion
		http.Error(w, "commitment is not convertible into $TARGET_RESOURCE", http.StatusUnprocessableEntity)
```

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment.go
> +	}
This is fine as defense in depth, but we ought to check `targetServiceType == sourceServiceType && targetResourceName == sourceResourceName` much earlier as a sanity check.

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment.go
> +	if dbCommitment.ConfirmBy == nil {
```suggestion
	if dbCommitment.ConfirmedAt != nil {
```

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment_test.go
> +			"confirm_by":        s.Clock.Now().Add(14 * day).Unix(),
Needs to be updated to `confirmed_at`, see previous remark.

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment_test.go
> +		Body:         commitment,
If `commitment` is only used once, I'd rather have it inline to reduce the need for scrolling while reading.

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment_test.go
> +	}
Can be written more compactly with `assert.DeepEqual(t, "commitment amount", originalCommitment.Amount, 18)`. For the other stuff analogously.

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment.go
> +	err := p.DB.SelectOne(&dbCommitment, `SELECT pc.* FROM project_commitments pc WHERE pc.id = $1`, commitmentID)
We should not allow grabbing commitments from foreign projects:

```suggestion
	err := p.DB.SelectOne(&dbCommitment, findProjectCommitmentByIDQuery, commitmentID, targetProject.ID)
```

Then `targetProject` can be just `project`. The testcases consequently need to be adjusted to not convert between projects (and indeed, there should be a testcase that you cannot convert a foreign commitment without transferring it first).

2024-09-17 12:26 UTC, majewsky commented on internal/api/commitment_test.go
> +	// Check resulting empty commitment from conversion calculation (remainderAmount > 0)
Comment needs clarification.

2024-09-17 13:40 UTC, VoigtS commented on internal/api/commitment.go
> +	err := p.DB.SelectOne(&dbCommitment, `SELECT pc.* FROM project_commitments pc WHERE pc.id = $1`, commitmentID)
I implemented the query and adjusted the unit tests accordingly.

2024-09-17 13:54 UTC, VoigtS commented on internal/api/commitment.go
> +		http.Error(w, "commitment is not convertible", http.StatusUnprocessableEntity)
I included the target resource into this error message.

2024-09-17 15:08 UTC, VoigtS commented on internal/api/commitment_test.go
> +	// Check resulting empty commitment from conversion calculation (remainderAmount > 0)
I changed it to the following, more meaningful comment:
`Reject an amount that doesn't fit into the conversion rate (remainder > 0).`

2024-09-17 15:10 UTC, VoigtS commented on internal/api/commitment.go
> +	}
I impelemented an early check now.
However, I keep this section in tact as a defense in depth as you said, because here we are able to explictly check against the `azResourceID`.

2024-09-17 15:16 UTC, VoigtS commented on internal/api/commitment.go
> +	}
You are correct, the commitments still exist and should be able to be operated on regardless if the resource itself accepts commitments. I noticed the `GET` method also checked against this case, I removed it there too.
That's because the conversion of a commitment requires a GET of the convertibles first if we are operating on UI level.

2024-09-17 15:21 UTC, VoigtS commented on internal/api/commitment_test.go
> +	}
I implemented this version now. However this is the only remaining part to adjust, because the conversion to a different project is now prohibited.

2024-09-17 15:36 UTC, VoigtS commented on internal/api/commitment_test.go
> +		Body:         commitment,
The body's are now inline as requested.

2024-09-18 12:39 UTC, majewsky approved these changes
I added two commits. One for nitpicks, and one to extend the audit event format to include all participating commitments. Please merge if this is to your liking.

2024-09-18 13:38 UTC, VoigtS commented
Thank you, the nitpicks I missed, because I was focused on the ID checks wich made me miss some parts. The rework of the Auditevent seems fine to me as well.

2024-09-18 13:38 UTC, merged