Add max quota configuration for project level
sapcc/limes pull request #600
Opened 2024-11-13 13:40 UTC by VoigtS

We would like to introduce the `max quota` configuration not only on domain level, but on project level as well. Because this requirment is different from the domain level one, a new field gets introduced to the same API endpoint which triggers if a user accesses it with project level privileges.

I am unsure about the naming of the db columns. I kept the orignal domain column name for now. I'm open to rename it as well if it is required. 

Before this gets published, the Oslo policies need to be updated, because the `project:max_quota_edit` role was originally used for the domain level. The `domain:max_quota_edit` role needs to be added as well.

2024-11-13 15:30 UTC, majewsky commented on internal/db/models.go
> +	MaxQuotaFromProject     *uint64             `db:"max_quota_from_project"`
It's becoming evident to me that the original `max_quota_from_admin` naming was flawed and should be fixed (Postgres has `ALTER TABLE ... RENAME` for this purpose). "From admin" vs. "from project" is not a good contrast because there also exists admins on the project level (but "from admin" refers to admins on the domain level). I suggest:
```suggestion
	MaxQuotaFromOutsideAdmin *uint64             `db:"max_quota_from_outside_admin"`
	MaxQuotaFromLocalAdmin   *uint64             `db:"max_quota_from_local_admin"`
```

2024-11-13 18:07 UTC, VoigtS commented on internal/db/models.go
> +	MaxQuotaFromProject     *uint64             `db:"max_quota_from_project"`
I updated the naming scheme accordingly

2024-11-14 14:34 UTC, majewsky requested changes

2024-11-14 14:34 UTC, majewsky commented on internal/api/projects.go
> +		http.Error(w, "Forbidden", http.StatusForbidden)
I have two notes here.

1. The pattern for policy rule names is that the first part identifies the object whose attributes are being changed. Since these endpoints update project quota constraints, all policies shall be `project:...` instead of `domain:...`. (Compare to the state before, where `project:edit_max_quota` was only accessible to domain admins.)
2. For editing `max_quota_from_local_admin`, I would like to avoid policy rule sprawl and reuse `project:edit` (which used to refer to editing of quotas, and currently refers to editing of commitments).

All in all, while also noting that domain admins are also project admins by inheritance:

```suggestion
	if !token.Require("project:edit") {
		return
	}
	domainAccess := token.Check("project:edit_as_outside_admin")
```

2024-11-18 13:46 UTC, majewsky approved these changes

2024-11-18 14:28 UTC, merged