Add support for AZ-separated quotas
sapcc/limes pull request #614
Opened 2024-11-29 14:51 UTC by VoigtS

This implementation handles the introduction of resource topologies. This allows the handling of synchronizing AZ-aware and AZ-separated quotas with the backend. 
The plugins will check if a liquid provides a valid toplogy. Invalid AZ's that are detected during scrapes will be rejected. Scraped AZ-separated quota will be included into the `backend_quota` column that resides in the `project_az_resources` table. From limes quota will then be synced with the backend if necessary. The `backend_quota` values will then be updated to the calculated `quota` values.

This will be a draft for now for the following reasons:
* The AZ key sorting in the uitlity functions might be able to be improved.
* `MatchLiquidReportToTopology` might collect the errors for all resources instead of failing at the first mismatch.
* SetQuota required a new type to support passing through the AZ-aware qutoas to the backend. We might have to adjust the naming of the structure and its contents.

TODOS:
- [ ] Adjust the algorithm to not provide base quota in any for az-separated resources.
- [ ] Cleanup steps involving `ResourceBehavior.CommitmentIsAZAware`

2024-12-05 14:13 UTC, majewsky requested changes

2024-12-05 14:13 UTC, majewsky commented on internal/collector/sync_quota_to_backend.go
> +	`)
This will also fill `backend_quota` for resources with AZAwareResourceTopology, which is not what we want. You're not seeing this behavior in your test because you fill `quota` manually for AZSeparatedResourceTopology resources only. But in real life, ACPQ will fill `quota` for AZAwareResourceTopology resources as well.

2024-12-05 14:13 UTC, majewsky commented on internal/datamodel/apply_computed_project_quota.go
> +						target[az][resourceID].Desired = cfg.ProjectBaseQuota - target[az][resourceID].Allocated
`Desired` is not computed on top of `Allocated`:
```suggestion
						target[az][resourceID].Desired = cfg.ProjectBaseQuota
```

2024-12-05 14:52 UTC, VoigtS commented on internal/api/commitment.go
> +	if resInfo.Topology != liquid.FlatResourceTopology {
I reversed the statements as described.

2024-12-05 14:53 UTC, VoigtS commented on internal/api/commitment_test.go
> -			commitment_is_az_aware: true
You are right. I removed them at the other parts, those were left over.

2024-12-05 14:55 UTC, VoigtS commented on internal/plugins/utils.go
> +	errs := []error{}
I included this fix while fixing the error collecting in the same codeblock.

2024-12-05 14:57 UTC, VoigtS commented on internal/plugins/capacity_liquid.go
> +		}
This is now fixed. It was implemented correctly in the test file. The transfer to the liquid clients was messed up.

2024-12-05 14:58 UTC, VoigtS commented on internal/plugins/liquid.go
> +	}
This is now fixed. It was implemented correctly in the test file. The transfer to the liquid clients was messed up.

2024-12-05 15:22 UTC, VoigtS commented on internal/plugins/utils.go
> +}
This is now fixed. It required a slice.Collect in order to sort, because maps.Keys returns an iterator. The type casts are now removed as well.

2024-12-05 15:31 UTC, VoigtS commented on internal/plugins/utils.go
> +		}
I fixed all occurences that showed up.

2024-12-05 15:47 UTC, VoigtS commented on internal/core/plugin.go
> +
I changed the datatype accordingly.

2024-12-05 18:42 UTC, VoigtS commented on internal/collector/scrape.go
>  			// quotas into if enabled
This is now implemented. I also added a testcase for it by deleting `az-two` from the resource `things`.

2024-12-06 09:42 UTC, VoigtS commented on internal/collector/sync_quota_to_backend.go
> +	`)
You are right. By using the service ID I was disregarding the toplogy of the services underlying toplogy. I changed it so the quota snyc collects the affected resource IDs and only operates on them.

2024-12-06 12:58 UTC, majewsky requested changes
We're getting there. A few more nitpicks, and here's a big thing on top: I don't know how to flag this on a specific line, so I'm going to write it here. If the code works the same as in my head, we will have a neverending series of useless quota syncs on resources with AZSeparatedResourceTopology. As per the spec, these resources should have `ResourceUsageReport.Quota == nil` (i.e. no total quota should be reported), which means that `project_resources.backend_quota` will be empty. ACPQ currently always fills `project_resources.quota` for the resources that it operates on, so on the resource level, we always have `quota != backend_quota` and therefore a quota sync is forced during each ACPQ run.

My gut feeling is that ACPQ should just not fill `project_resources.quota` for AZSeparateResourceTopology resources. (The absence of the overall quota could then also be a trigger for the UI to hide the region-wide quota/usage bar.) But I have not finished thinking about whether that will induce corner cases elsewhere.

2024-12-06 12:58 UTC, majewsky commented on internal/collector/sync_quota_to_backend.go
> +			targetAZQuotasInDB[resourceName] = make(map[liquid.AvailabilityZone]liquid.AZResourceQuotaRequest)
This should not overwrite existing values from other AZs:
```suggestion
			if targetAZQuotasInDB[resourceName] == nil {
				targetAZQuotasInDB[resourceName] = make(map[liquid.AvailabilityZone]liquid.AZResourceQuotaRequest)
			}
```

2024-12-06 12:58 UTC, majewsky commented on internal/datamodel/apply_computed_project_quota_test.go
> +	actual, _ := acpqComputeQuotas(input, cfg, constraints, liquid.ResourceInfo{})
We're testing with empty-string as Topology here, which is not supposed to be a supported value. `expectACPQResult` should instead take a `liquid.ResourceInfo` argument, and all existing calls should be updated to take either Flat or AZAware as appropriate.

2024-12-06 12:58 UTC, majewsky commented on internal/plugins/capacity_liquid.go
> +			errs = append(errs, fmt.Errorf("service: %s, resource: %s: %w", p.ServiceType, resourceName, err))
This does not need to specify the service type, since the caller already adds that to the error message:
```suggestion
			errs = append(errs, fmt.Errorf("resource: %s: %w", resourceName, err))
```
Same in the QuotaPlugin below.

2024-12-06 12:58 UTC, majewsky commented on internal/plugins/liquid.go
>  	}
It doesn't let me do a suggestion here for some reason, but the type already nearly matches, so this can be shortened to `req := liquid.ServiceQuotaRequest{Resources: quotaReq}`.

2024-12-06 12:58 UTC, majewsky commented on internal/plugins/utils.go
> +func SortMapKeys[M map[K]V, K ~string, V any](mapToSort M) []K {
I forgot to nitpick this before because of the larger remark on this function, but `Sort` implies that this function operates in-place, which it does not:
```suggestion
func SortedMapKeys[M map[K]V, K ~string, V any](mapToSort M) []K {
```

2024-12-06 13:17 UTC, VoigtS commented on internal/plugins/liquid.go
>  	}
You are correct. I changed the value assignment as suggested.

2024-12-06 13:18 UTC, VoigtS commented on internal/plugins/utils.go
> +func SortMapKeys[M map[K]V, K ~string, V any](mapToSort M) []K {
I included this change in a separate commit, because I changed all referenced to the function with it.

2024-12-06 13:42 UTC, VoigtS commented on internal/datamodel/apply_computed_project_quota_test.go
> +	actual, _ := acpqComputeQuotas(input, cfg, constraints, liquid.ResourceInfo{})
I included this suggestion. Each test case now provides a specific topology.

2024-12-06 13:45 UTC, VoigtS commented on internal/plugins/capacity_liquid.go
> +			errs = append(errs, fmt.Errorf("service: %s, resource: %s: %w", p.ServiceType, resourceName, err))
I made a separate commit for it where I adjusted both.

2024-12-06 14:58 UTC, VoigtS commented
> We're getting there. A few more nitpicks, and here's a big thing on top: I don't know how to flag this on a specific line, so I'm going to write it here. If the code works the same as in my head, we will have a neverending series of useless quota syncs on resources with AZSeparatedResourceTopology. As per the spec, these resources should have `ResourceUsageReport.Quota == nil` (i.e. no total quota should be reported), which means that `project_resources.backend_quota` will be empty. ACPQ currently always fills `project_resources.quota` for the resources that it operates on, so on the resource level, we always have `quota != backend_quota` and therefore a quota sync is forced during each ACPQ run.
> 
> My gut feeling is that ACPQ should just not fill `project_resources.quota` for AZSeparateResourceTopology resources. (The absence of the overall quota could then also be a trigger for the UI to hide the region-wide quota/usage bar.) But I have not finished thinking about whether that will induce corner cases elsewhere.

I did not know that it is intended for the liquid to return a nil value if it has the AZ separated toplogy. I included a skip for setting the ACPQ quota and provided an explanation for it.

2024-12-06 15:54 UTC, majewsky requested changes
I have pushed a few nitpick fixes. Also, there is one last bigger thing:

2024-12-06 15:54 UTC, majewsky commented on internal/datamodel/apply_computed_project_quota.go
> +		}
Because of this, `servicesWithUpdatedQuota` will never be filled for AZ-separated resources, which means that quota syncs will never be triggered from ACPQ for those resources. For AZ-separated resources, `servicesWithUpdatedQuota` needs to be filled during `acpqUpdateAZQuotaQuery` instead.

2024-12-06 16:53 UTC, VoigtS commented on internal/datamodel/apply_computed_project_quota.go
> +		}
I included a fix in PR: [717a028](https://github.com/sapcc/limes/pull/614/commits/717a02832ecaa78cc2e5616a460c3be27b84c13b) `servicesWithUpdatedQuota` will be declared before `acpqUpdateAZQuotaQuery` takes place and will populate the fields with the required service IDs.

2024-12-09 14:24 UTC, majewsky approved these changes
Awesome, thanks!

2024-12-09 14:25 UTC, merged