Liquid nova report capacity
sapcc/limes pull request #628
Opened 2024-12-13 15:57 UTC by Varsius

Checklist:

- [x] If this PR is about a plugin, I tested the plugin against an OpenStack cluster.
- [x] I updated the documentation to describe the semantical or interface changes I introduced.

2024-12-17 09:27 UTC, majewsky commented on internal/liquids/nova/hypervisor_subcapacity.go
> +		// TODO: What should be the naming here? We list subcapacities for cores, ram and instances on the same split flavor capacity
I don't like there being multiple subcapacities for different aspects of the same thing. Let's have this as a single subcapacity with `Capacity: 0,` and all the actual data in attributes shaped like the old subcapacities.

2024-12-17 09:29 UTC, majewsky commented on internal/liquids/nova/usage.go
> +		if err = json.Unmarshal(subres.Attributes, &attrs); err != nil { // TODO: Unmarshalling here + marshalling when building the subresources seems inefficient
Consider passing the subresources as type `liquid.SubresourceBuilder[A]` instead.

2024-12-18 15:18 UTC, majewsky commented on internal/liquids/nova/capacity.go
> +}
Please use the equivalent functions from package liquids:

https://github.com/sapcc/limes/blob/2dc280056b951470d394a219397eb72cfe70ac89/internal/liquids/utils.go#L69-L80

2024-12-18 15:18 UTC, majewsky commented on internal/liquids/nova/hypervisor_subcapacity.go
> +	CoresSubcapacities     []liquid.Subcapacity
Comment is not relevant to this new type and can be removed.

2025-01-07 12:52 UTC, majewsky requested changes

2025-01-07 12:52 UTC, majewsky commented on internal/liquids/nova/hypervisor_subcapacity.go
> +	})
It's more idiomatic to use SubcapacityBuilder + Finalize. I did not note this up ahead because there is a case there to reuse the single serialization across three Subresources.

2025-01-07 12:52 UTC, majewsky commented on internal/liquids/nova/capacity.go
> +			}
```suggestion
			amount = min(amount, maxAmount)
```

2025-01-07 12:52 UTC, majewsky commented on internal/liquids/nova/capacity.go
> +			}
Can be simplified with NormalizeAZ.

2025-01-13 10:48 UTC, majewsky approved these changes
Code's looking good now, thanks!

I will add a commit for the documentation once I get to it, hopefully tomorrow.

2025-01-13 15:33 UTC, majewsky requested changes

2025-01-13 15:33 UTC, majewsky commented on internal/core/translation_rule.go
> +			VideoMemoryMiB: &limes.ValueWithUnit{Unit: limes.UnitMebibytes, Value: *in.Attributes.Flavor.VideoMemoryMiB},
This should not panic if the VideoMemoryMiB field is nil.

2025-01-15 14:28 UTC, majewsky requested changes
I have finished the documentation; please counter-review. Also, two comments on the TranslationRule implementations:

2025-01-15 14:28 UTC, majewsky commented on internal/core/translation_rule.go
> +				HWVersion      string  `json:"-"`
Nitpick: Since HWVersion is never serialized, it is irrelevant here (and also on `type oldFormat` below) and can be removed.

2025-01-15 14:28 UTC, majewsky commented on internal/core/translation_rule.go
> +			Usage:            in.Usage,
This only covers the format for pooled resources, where only one value is given for capacity and usage. For split flavors, `CapacityVector` and `UsageVector` need to be filled. A test should be added for the split-flavor case.

2025-01-16 08:30 UTC, Varsius commented on internal/core/translation_rule.go
> +			Usage:            in.Usage,
From what I understand, we do not report subcapacities on split-flavors anymore. This was only done in the case we could not report on the pooled resources which is know always possible.

2025-01-20 10:01 UTC, majewsky commented on internal/core/translation_rule.go
> +			Usage:            in.Usage,
You're right! I got confused because `type Subcapacity` did not have "deprecated" in it. I have renamed it to `type DeprecatedSubcapacity` now.

2025-01-20 10:01 UTC, majewsky approved these changes

2025-01-20 10:03 UTC, merged